### ISSUE TITLE
プレビルトイメージを用意する

### ISSUE THREAD

**Issue by kory33** [GiganticMinecraft/SeichiRanking#149]
基盤となるイメージは固定であって各位でビルドする必要が無いっぽいので、
[dockers](https://github.com/GiganticMinecraft/dockers)等に参照可能なイメージを用意してしまって良さそうです。

**Comment by unchama** [comment]
ふときになったのですが、dockersにイメージを集約する理由ってありますか？
masterブランチ反映時にコードを含んだproduction用途にも使えるイメージをbuild+publishしとこうかなと思ったんですが、dockersにまとめようと思うと、Github Actionsが発火するタイミングが"SeichiRankiingのmaster更新時"じゃなくって"dockersのmaster更新時"になるので、これどうなんだろうとなっています。SeichiRankingリポジトリ内でdocker imageをpublishした方が良さげですかね？
