### ISSUE TITLE
年間ランキングの読み込みに時間がかかりすぎて504が返される

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/SeichiRanking#172]
SSIA

**Comment by KisaragiEffective** [comment]
単純に`LIMIT`してないので全表操作が走ってすごく時間がかかっていそう

**Comment by KisaragiEffective** [comment]
そういうわけでもなさそう

**Comment by KisaragiEffective** [comment]
やっぱりソートが悪そう。
試しに
```sql
SELECT break_count, yrt.uuid from yearly_ranking_table yrt, playerdata pd where yrt.uuid = pd.uuid COLLATE utf8_general_ci order by break_count desc;
```
を走らせたら45秒かかったのでもうすこしどうにかなってほしい。

**Comment by KisaragiEffective** [comment]
PHP側でソートすればこんなに時間かからないのだろうか？

**Comment by KisaragiEffective** [comment]
> やっぱりソートが悪そう。 試しに
> 
> ```sql
> SELECT break_count, yrt.uuid from yearly_ranking_table yrt, playerdata pd where yrt.uuid = pd.uuid COLLATE utf8_general_ci order by break_count desc;
> ```
> 
> を走らせたら45秒かかったのでもうすこしどうにかなってほしい。

これWHERE clauseで結合しているのが悪いのではという指摘があった。

**Comment by kory33** [comment]
クエリのパフォーマンスを改善しようとするよりも、バッチでランキングデータを移す時に非正規化されたテーブルにランキングを(事前計算した形で)格納しておいて、readが一瞬でできるようにする、といったアーキテクチャ上の改善をした方が良さそうです

**Comment by KisaragiEffective** [comment]
TODO: `[Span] =>> (uuid: UUID, break_rank: PeriodicRanking[Break, Span], build_rank: PeriodicRanking[Build, Span], vote_rank: PeriodicRanking[Vote, Span], play_rank: PeriodicRanking[Play, Span], lastQuit: DateTime)` みたいな感じのあれを生やしてAPIのリードをそっちに変更する

**Comment by inductor** [comment]
TODO: MySQL改善でよくなったか確認する

**Comment by inductor** [comment]
なってない

**Comment by inductor** [comment]
@KisaragiEffective  https://ranking-gigantic.seichi.click/#page=1&type=break&duration=yearly 全然遅く無さそうだよ

**Comment by KisaragiEffective** [comment]
@inductor :tada:
