### ISSUE TITLE
Copyright infringement

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/SeichiRanking#189]
https://github.com/MineTheCube/MojangAPI からのファイルが明示的にライセンスされていないので再配布できない。よってライセンス違反を引き起こしているので、 https://github.com/elyby/mojang-api に乗り換えるべき

**Comment by Lucky3028** [comment]
（SeichiRankingくんもライセンスを明示してほしい）

**Comment by KisaragiEffective** [comment]
> （SeichiRankingくんもライセンスを明示してほしい）

@curosuke さんが主コミッターなので、curosukeさんがどう回答されるかによりそう

**Comment by unchama** [comment]
これ、ぼちぼち乗り換えましょうか(現地になんらかのライセンス明示的な付与を依頼するissue出してもらってますが、このリポジトリおそらく数年単位で放置されとる)

**Comment by kory33** [comment]
乗り換えるというと、普通に一から作り直す感じですか？

**Comment by nakano-shingo** [comment]
MITライセンス付与しちゃいましょう！

**Comment by KisaragiEffective** [comment]
とりあえず、以降は　#253 で
