### ISSUE TITLE
composer.jsonの改善

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/SeichiRanking#205]
以下の4点:
https://github.com/GiganticMinecraft/SeichiRanking/blob/2af79a6a6c6901d5f4547a67df178f8539bff804/composer.json#L2

`giganticminecraft/seichiranking`にでもするべき (composer v2は大文字を受け付けない)。

https://github.com/GiganticMinecraft/SeichiRanking/blob/2af79a6a6c6901d5f4547a67df178f8539bff804/composer.json#L3

当然違う。

https://github.com/GiganticMinecraft/SeichiRanking/blob/2af79a6a6c6901d5f4547a67df178f8539bff804/composer.json#L4

同上。

https://github.com/GiganticMinecraft/SeichiRanking/blob/2af79a6a6c6901d5f4547a67df178f8539bff804/composer.json#L5

README.mdによればNo Licenseなのでウソ。

**Comment by KisaragiEffective** [comment]
@inductor 以上の理由により再オープン

**Comment by inductor** [comment]
はい
